/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScrollHeadline {
        "id": string;
    }
}
declare global {
    interface HTMLScrollHeadlineElement extends Components.ScrollHeadline, HTMLStencilElement {
    }
    var HTMLScrollHeadlineElement: {
        prototype: HTMLScrollHeadlineElement;
        new (): HTMLScrollHeadlineElement;
    };
    interface HTMLElementTagNameMap {
        "scroll-headline": HTMLScrollHeadlineElement;
    }
}
declare namespace LocalJSX {
    interface ScrollHeadline {
        "id"?: string;
    }
    interface IntrinsicElements {
        "scroll-headline": ScrollHeadline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scroll-headline": LocalJSX.ScrollHeadline & JSXBase.HTMLAttributes<HTMLScrollHeadlineElement>;
        }
    }
}
