/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FinancingCalculator {
        "durationMonths": number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "duration-months"?: number;
        "price": number;
    }
    interface ScrollHeadline {
        "id": string;
    }
}
declare global {
    interface HTMLFinancingCalculatorElement extends Components.FinancingCalculator, HTMLStencilElement {
    }
    var HTMLFinancingCalculatorElement: {
        prototype: HTMLFinancingCalculatorElement;
        new (): HTMLFinancingCalculatorElement;
    };
    interface HTMLScrollHeadlineElement extends Components.ScrollHeadline, HTMLStencilElement {
    }
    var HTMLScrollHeadlineElement: {
        prototype: HTMLScrollHeadlineElement;
        new (): HTMLScrollHeadlineElement;
    };
    interface HTMLElementTagNameMap {
        "financing-calculator": HTMLFinancingCalculatorElement;
        "scroll-headline": HTMLScrollHeadlineElement;
    }
}
declare namespace LocalJSX {
    interface FinancingCalculator {
        "durationMonths"?: number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "duration-months"?: number;
        "price"?: number;
    }
    interface ScrollHeadline {
        "id"?: string;
    }
    interface IntrinsicElements {
        "financing-calculator": FinancingCalculator;
        "scroll-headline": ScrollHeadline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "financing-calculator": LocalJSX.FinancingCalculator & JSXBase.HTMLAttributes<HTMLFinancingCalculatorElement>;
            "scroll-headline": LocalJSX.ScrollHeadline & JSXBase.HTMLAttributes<HTMLScrollHeadlineElement>;
        }
    }
}
